### ISSUE TITLE
No support for non standard MQTT Port

### ISSUE THREAD

**Issue by joshuakohut77** [tobinbrooke/icue2mqtt#20]
Unless I'm missing something it does not look like this has support for anything besides port 1883. 
It would be nice to add support for non standard ports. I think this would be relatively simple to change. 

I'm not a cs coder so I'm making some assumptions but in the file [MqttClientUtil.cs](https://github.com/tobinbrooke/icue2mqtt/blob/master/icue2mqtt/MqttClientUtil.cs), on line 74. I believe you can add a second parameter which is the port. 
You can see an example of this in the MQTTnet file [here](https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet/Client/Options/MqttClientOptionsBuilder.cs) starting with line 116.

Ideally we can add a new optional "mqttPort" property. Default to 1883 for most people and to not break any previous installs. 

Edit:
I'm not sure how to compile the program otherwise I would test this myself. If you can provide a compiled version with the changes I would be willing to test this for you.

**Comment by tobinbrooke** [comment]
Have you tried adding the port to the url seperated by a colon for example 127.0.0.1:8989
The code the the client just combines them in this way anyway

**Comment by joshuakohut77** [comment]
Yes I did try that. When I do so I get the following error but using "192.168.5.3:8989" (where 8989 is my real port)
```
Failed to connect to MQTT broker.: No such host is known. 
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at icue2mqtt.MqttClientUtil.ConnectToMqttBrokerAsync(Boolean reconnecting) in C:\Users\legend\Downloads\icue2mqtt-master\icue2mqtt-master\icue2mqtt\MqttClientUtil.cs:line 100
```
However I believe everything else is setup because if I add the <ip-address> without the port at the end I get an expected error
```
Failed to connect to MQTT broker.: No connection could be made because the target machine actively refused it. [::ffff:192.168.5.10]:1883 
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at icue2mqtt.MqttClientUtil.ConnectToMqttBrokerAsync(Boolean reconnecting) in C:\Users\legend\Downloads\icue2mqtt-master\icue2mqtt-master\icue2mqtt\MqttClientUtil.cs:line 100
```

**Comment by tobinbrooke** [comment]
added optional property mqttOverridePortString which if not present in properties.json will use default port else if the value is convertable to integer will set the broker port when creating the client
